# -*- coding: utf-8 -*-
"""Copia de AIG4B-Clase-9-Segmentacion-FCN-UNET-SAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lTk24Uag9WRU-ZTHhKeYTiDJ-cyhiq0

# **Materia: IA para Ingeniería Biomédica**
## Clase 9 (Parte 2): Segmentación con FCN, UNET y SAM

**Profesores:** Paulo Veiga · Marco Sanchez Sorondo

En esta notebook vamos a **comparar tres paradigmas** de segmentación que vimos en la clase teórica:

1. **FCN (Fully Convolutional Network)** — el modelo base, simple y conceptual.
2. **UNET** — la arquitectura biomédica por excelencia, con skip connections.
3. **SAM (Segment Anything Model)** — el foundation model promptable de Meta, sin entrenamiento previo.

Para que la comparación sea fair, los tres se evalúan sobre el **mismo dataset** y con **la misma métrica** (Dice).

### Stack

- **Dataset:** [`MedSegBench`](https://medsegbench.github.io/) — el "MedMNIST de la segmentación". Vamos a usar **Kvasir** (segmentación de pólipos en colonoscopía).
- **FCN:** implementado a mano con encoder ResNet18 + capa 1×1 + upsample.
- **UNET:** vía `segmentation-models-pytorch` (la librería estándar en producción).
- **SAM:** vía el paquete oficial `segment-anything` de Meta (versión ViT-B).

### Estructura

1. **Setup** — instalación y descargas
2. **Dataset** — cargar y visualizar Kvasir
3. **Modelo 1: FCN** — entrenamiento, evaluación, visualización
4. 🎯 **Tarea 1** — Experimentar con FCN
5. **Modelo 2: UNET** — entrenamiento, evaluación, visualización
6. 🎯 **Tarea 2** — Experimentar con UNET
7. **Modelo 3: SAM zero-shot** — evaluación con prompts
8. 🎯 **Tarea 3** — Experimentar con SAM
9. **Comparativa final**
10. 🎯 **Tarea opcional 1** — SAM 2 sobre Kvasir
11. 🎯 **Tarea opcional 2** — SAM 3 sobre Kvasir
12. 🎯 **Tarea opcional 3** — Multi-clase con BUSI
13. **Cierre**

> 📝 **Las tareas opcionales (10, 11 y 12), aunque no son obligatorias, suman puntos a la nota final.** Hacerlas muestra interés y compromiso, y quedan registradas en la entrega.

## 1. Setup

Verificamos GPU + instalamos las tres dependencias clave: **medsegbench** (datasets), **segmentation-models-pytorch** (UNET) y **segment-anything** (SAM).

> El download de pesos de SAM-ViT-B es de ~375 MB. La primera vez tarda 1-2 min.
"""

import torch

if torch.cuda.is_available():
    !nvidia-smi
    print(f"\n✅ GPU detectada: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️  No se detectó GPU. Andá a Runtime → Change runtime type → T4 GPU.")

!pip install -q medsegbench segmentation-models-pytorch
!pip install -q git+https://github.com/facebookresearch/segment-anything.git

# Pesos de SAM ViT-B (~375 MB)
import os, urllib.request
SAM_CKPT = "sam_vit_b_01ec64.pth"
if not os.path.exists(SAM_CKPT):
    url = f"https://dl.fbaipublicfiles.com/segment_anything/{SAM_CKPT}"
    print(f"Descargando {SAM_CKPT}...")
    urllib.request.urlretrieve(url, SAM_CKPT)
print(f"✅ Pesos de SAM disponibles: {SAM_CKPT}")

"""## 2. Dataset: Kvasir (segmentación de pólipos en colonoscopía)

Cargamos el dataset desde MedSegBench. Es un dataset endoscópico donde la tarea es segmentar **pólipos** — pequeñas protuberancias en la mucosa intestinal que pueden ser precursoras de cáncer colorrectal. Detectarlas y delinearlas durante la colonoscopía es uno de los procedimientos diagnósticos más importantes de la gastroenterología.

- **Modalidad:** endoscopía (RGB).
- **Clases:** binaria (pólipo vs. fondo).
- **Splits:** train / val / test pre-divididos.
- **Tamaño:** usamos `size=256` (256×256 píxeles) — buen balance entre velocidad y detalle.

Definimos dos versiones del dataset:
- **`*_train`**: con normalización ImageNet — para entrenar FCN y UNET (que usan encoders pre-entrenados).
- **`*_viz`**: sin normalización — para visualizar y para SAM (que espera imágenes uint8 sin normalizar).

"""

from medsegbench import KvasirMSBench
import torchvision.transforms as T

# Transforms
img_train_tf = T.Compose([
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
img_viz_tf = T.Compose([T.ToTensor()])
mask_tf    = T.Compose([T.ToTensor()])

# Para entrenar (con normalización ImageNet)
train_ds = KvasirMSBench(split="train", size=256, download=True,
                         transform=img_train_tf, target_transform=mask_tf)
val_ds   = KvasirMSBench(split="val",   size=256, download=True,
                         transform=img_train_tf, target_transform=mask_tf)
test_ds  = KvasirMSBench(split="test",  size=256, download=True,
                         transform=img_train_tf, target_transform=mask_tf)

# Para visualización y SAM (sin normalizar)
test_viz = KvasirMSBench(split="test",  size=256, download=False,
                         transform=img_viz_tf, target_transform=mask_tf)

print(f"Train: {len(train_ds)} imágenes")
print(f"Val:   {len(val_ds)} imágenes")
print(f"Test:  {len(test_ds)} imágenes")

img, mask = train_ds[0]
print(f"\nImage shape: {tuple(img.shape)}, dtype: {img.dtype}")
print(f"Mask  shape: {tuple(mask.shape)}, dtype: {mask.dtype}, unique: {torch.unique(mask).tolist()}")

import matplotlib.pyplot as plt

# Visualizamos 4 ejemplos del dataset (versión sin normalizar)
fig, axes = plt.subplots(3, 4, figsize=(14, 10))
for i in range(4):
    img, mask = test_viz[i]
    img_np = img.permute(1, 2, 0).numpy()
    mask_np = mask.squeeze().numpy()

    axes[0, i].imshow(img_np);            axes[0, i].set_title(f"Imagen #{i}");  axes[0, i].axis("off")
    axes[1, i].imshow(mask_np, cmap="gray"); axes[1, i].set_title("Máscara GT"); axes[1, i].axis("off")
    axes[2, i].imshow(img_np)
    axes[2, i].imshow(mask_np, cmap="Reds", alpha=0.4)
    axes[2, i].set_title("Overlay");      axes[2, i].axis("off")

plt.tight_layout(); plt.show()

"""## 3. Modelo 1 — FCN (Fully Convolutional Network)

Implementamos un **FCN mínimo** que refleja la receta del slide:

1. **Encoder convolucional** (ResNet18 sin las capas densas finales) → comprime la imagen.
2. **Convolución 1×1** → produce un mapa de logits con `num_classes` canales.
3. **Upsample bilineal** → estira el mapa hasta el tamaño original de la imagen.

**Lo que esperamos ver:** las máscaras predichas van a tener **bordes borrosos**, porque el upsample bilineal no recupera los detalles que se perdieron en el encoder. Este es exactamente el problema que motivó UNET.

"""

import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as tv_models

class SimpleFCN(nn.Module):
    """FCN didáctico: encoder ResNet18 + 1x1 conv + upsample bilineal."""
    def __init__(self, num_classes: int = 1, pretrained: bool = True):
        super().__init__()
        weights = "DEFAULT" if pretrained else None
        backbone = tv_models.resnet18(weights=weights)
        # Encoder: todas las capas conv del ResNet (descartamos avgpool + fc)
        self.encoder = nn.Sequential(
            backbone.conv1, backbone.bn1, backbone.relu, backbone.maxpool,
            backbone.layer1, backbone.layer2, backbone.layer3, backbone.layer4,
        )
        # Clasificador 1x1: 512 canales del ResNet → num_classes
        self.classifier = nn.Conv2d(512, num_classes, kernel_size=1)

    def forward(self, x):
        original_size = x.shape[-2:]
        x = self.encoder(x)            # [B, 512, H/32, W/32]
        x = self.classifier(x)         # [B, C,   H/32, W/32]
        x = F.interpolate(x, size=original_size, mode="bilinear", align_corners=False)
        return x                       # [B, C,   H,    W]

# Test rápido de la arquitectura
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
fcn = SimpleFCN(num_classes=1).to(device)
dummy = torch.randn(2, 3, 256, 256).to(device)
with torch.no_grad():
    out = fcn(dummy)
print(f"Input:  {tuple(dummy.shape)}")
print(f"Output: {tuple(out.shape)}")
print(f"Parámetros entrenables: {sum(p.numel() for p in fcn.parameters() if p.requires_grad)/1e6:.2f}M")

"""### Funciones auxiliares de entrenamiento y métrica

Definimos un loop de entrenamiento corto y la métrica **Dice** — que vamos a reusar para los tres modelos. El Dice mide qué tan parecidas son dos máscaras (1 = idénticas, 0 = sin solape).

"""

from torch.utils.data import DataLoader
import segmentation_models_pytorch as smp

BATCH_SIZE = 16
EPOCHS = 10
LR = 1e-3

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2)


def dice_score(pred_mask: torch.Tensor, true_mask: torch.Tensor, eps: float = 1e-6) -> float:
    """Dice score binario sobre tensores [B, 1, H, W] con valores en {0, 1}."""
    pred_mask = pred_mask.float()
    true_mask = true_mask.float()
    intersection = (pred_mask * true_mask).sum(dim=(1, 2, 3))
    union = pred_mask.sum(dim=(1, 2, 3)) + true_mask.sum(dim=(1, 2, 3))
    dice = (2 * intersection + eps) / (union + eps)
    return dice.mean().item()


def train_model(model, train_loader, val_loader, epochs=EPOCHS, lr=LR):
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = smp.losses.DiceLoss(smp.losses.BINARY_MODE, from_logits=True)

    history = {"train_loss": [], "val_dice": []}
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            logits = model(x)
            loss = loss_fn(logits, y)
            loss.backward(); optimizer.step()
            epoch_loss += loss.item() * x.size(0)
        epoch_loss /= len(train_loader.dataset)

        # Validación
        model.eval()
        val_dices = []
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                pred = (model(x).sigmoid() > 0.5).float()
                val_dices.append(dice_score(pred, y))
        val_dice = sum(val_dices) / len(val_dices)

        history["train_loss"].append(epoch_loss)
        history["val_dice"].append(val_dice)
        print(f"Epoch {epoch+1:2d}/{epochs} · loss={epoch_loss:.4f} · val Dice={val_dice:.4f}")
    return history


def evaluate_dice(model, loader) -> float:
    model.eval()
    dices = []
    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            pred = (model(x).sigmoid() > 0.5).float()
            dices.append(dice_score(pred, y))
    return sum(dices) / len(dices)

"""### Entrenamos el FCN

10 epochs deberían tomar ~1-2 minutos en una T4.

"""

import time
fcn = SimpleFCN(num_classes=1, pretrained=True)

t0 = time.time()
fcn_history = train_model(fcn, train_loader, val_loader, epochs=EPOCHS)
fcn_train_time = time.time() - t0

fcn_test_dice = evaluate_dice(fcn, test_loader)
print(f"\n⏱ Tiempo de entrenamiento: {fcn_train_time:.1f} s")
print(f"📊 FCN — Dice en TEST: {fcn_test_dice:.4f}")

"""### Visualizamos las predicciones de FCN

Acá deberíamos ver la **firma del problema FCN**: máscaras con bordes borrosos o "redondeados", aunque la ubicación general del pólipo sea correcta.

"""

def visualize_predictions(model, dataset_viz, dataset_norm, n_samples=4, title="Modelo"):
    model.eval()
    fig, axes = plt.subplots(3, n_samples, figsize=(n_samples*3.2, 9))
    for i in range(n_samples):
        img_viz, mask = dataset_viz[i]
        img_norm, _   = dataset_norm[i]

        with torch.no_grad():
            logit = model(img_norm.unsqueeze(0).to(device))
            pred = (logit.sigmoid() > 0.5).float().squeeze().cpu().numpy()

        img_np  = img_viz.permute(1, 2, 0).numpy()
        mask_np = mask.squeeze().numpy()

        axes[0, i].imshow(img_np);            axes[0, i].set_title(f"#{i} — Imagen"); axes[0, i].axis("off")
        axes[1, i].imshow(mask_np, cmap="gray"); axes[1, i].set_title("Ground truth"); axes[1, i].axis("off")
        axes[2, i].imshow(pred, cmap="gray");    axes[2, i].set_title(f"{title} pred"); axes[2, i].axis("off")
    plt.tight_layout(); plt.show()

visualize_predictions(fcn, test_viz, test_ds, n_samples=4, title="FCN")

"""## 4. 🎯 Tarea 1 — Experimentar con FCN

Ya entrenaste un FCN básico. Ahora experimentá para entender qué lo limita y qué podría mejorarlo.

### Mínimo a probar

1. **Más epochs**: entrená 25 o 50 epochs. ¿Mejora el Dice o se estanca?
2. **Otro encoder**: cambiá a `resnet34` o `resnet50` modificando `SimpleFCN`. ¿Mejora la calidad o solo el tiempo de entrenamiento?
3. **Sin pretrained**: instanciá `SimpleFCN(pretrained=False)`. ¿Cuánto baja el Dice?

### Reflexión

- ¿Qué tipo de errores ves en las máscaras predichas?
- ¿En qué imágenes el FCN funciona razonablemente bien? ¿En cuáles falla?
- Si tuvieras que llevar este modelo a un endoscopio en producción, ¿qué cambiarías?

"""

# 🎯 TU EXPERIMENTO ACÁ

# Sugerencia: probá una de estas variantes y compará Dice vs. el FCN base
# Variante 1 — más epochs:
# fcn_v2 = SimpleFCN(num_classes=1, pretrained=True)
# train_model(fcn_v2, train_loader, val_loader, epochs=...)
# print(f"Test Dice: {evaluate_dice(fcn_v2, test_loader):.4f}")

# Variante 2 — sin pretrained:
# fcn_scratch = SimpleFCN(num_classes=1, pretrained=False)
# ...

# Tu código:
BATCH_SIZE = 16
EPOCHS = 10
LR = 1e-3

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2)


def dice_score(pred_mask: torch.Tensor, true_mask: torch.Tensor, eps: float = 1e-6) -> float:
    """Dice score binario sobre tensores [B, 1, H, W] con valores en {0, 1}."""
    pred_mask = pred_mask.float()
    true_mask = true_mask.float()
    intersection = (pred_mask * true_mask).sum(dim=(1, 2, 3))
    union = pred_mask.sum(dim=(1, 2, 3)) + true_mask.sum(dim=(1, 2, 3))
    dice = (2 * intersection + eps) / (union + eps)
    return dice.mean().item()


def train_model(model, train_loader, val_loader, epochs=EPOCHS, lr=LR):
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = smp.losses.DiceLoss(smp.losses.BINARY_MODE, from_logits=True)

    history = {"train_loss": [], "val_dice": []}
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            logits = model(x)
            loss = loss_fn(logits, y)
            loss.backward(); optimizer.step()
            epoch_loss += loss.item() * x.size(0)
        epoch_loss /= len(train_loader.dataset)

        # Validación
        model.eval()
        val_dices = []
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                pred = (model(x).sigmoid() > 0.5).float()
                val_dices.append(dice_score(pred, y))
        val_dice = sum(val_dices) / len(val_dices)

        history["train_loss"].append(epoch_loss)
        history["val_dice"].append(val_dice)
        print(f"Epoch {epoch+1:2d}/{epochs} · loss={epoch_loss:.4f} · val Dice={val_dice:.4f}")
    return history


def evaluate_dice(model, loader) -> float:
    model.eval()
    dices = []
    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            pred = (model(x).sigmoid() > 0.5).float()
            dices.append(dice_score(pred, y))
    return sum(dices) / len(dices)

fcn = SimpleFCN(num_classes=1, pretrained=True)

t0 = time.time()
fcn_history = train_model(fcn, train_loader, val_loader, epochs=EPOCHS)
fcn_train_time = time.time() - t0

fcn_test_dice = evaluate_dice(fcn, test_loader)
print(f"\n⏱ Tiempo de entrenamiento: {fcn_train_time:.1f} s")
print(f"📊 FCN — Dice en TEST: {fcn_test_dice:.4f}")

def visualize_predictions(model, dataset_viz, dataset_norm, n_samples=4, title="Modelo"):
    model.eval()
    fig, axes = plt.subplots(3, n_samples, figsize=(n_samples*3.2, 9))
    for i in range(n_samples):
        img_viz, mask = dataset_viz[i]
        img_norm, _   = dataset_norm[i]

        with torch.no_grad():
            logit = model(img_norm.unsqueeze(0).to(device))
            pred = (logit.sigmoid() > 0.5).float().squeeze().cpu().numpy()

        img_np  = img_viz.permute(1, 2, 0).numpy()
        mask_np = mask.squeeze().numpy()

        axes[0, i].imshow(img_np);            axes[0, i].set_title(f"#{i} — Imagen"); axes[0, i].axis("off")
        axes[1, i].imshow(mask_np, cmap="gray"); axes[1, i].set_title("Ground truth"); axes[1, i].axis("off")
        axes[2, i].imshow(pred, cmap="gray");    axes[2, i].set_title(f"{title} pred"); axes[2, i].axis("off")
    plt.tight_layout(); plt.show()

visualize_predictions(fcn, test_viz, test_ds, n_samples=4, title="FCN")

"""
Con 10 epochs:
⏱ Tiempo de entrenamiento: 38.0 s
📊 FCN — Dice en TEST: 0.7910
Con 25:
⏱ Tiempo de entrenamiento: 97.8 s
📊 FCN — Dice en TEST: 0.7934
Con 50:
⏱ Tiempo de entrenamiento: 194.3 s
📊 FCN — Dice en TEST: 0.7911
Parece que tanto para el de 25 como para el de 50, alrededor del numero 20 comienza a plancharse y mantenerse en un mismo valor.
"""
"""
Con 10 epochs y resnet 34:
⏱ Tiempo de entrenamiento: 58.4 s
📊 FCN — Dice en TEST: 0.7553
Con 10 epochs y resnet50:
⏱ Tiempo de entrenamiento: 102.1 s
📊 FCN — Dice en TEST: 0.7904
Por lo visto, lo unico que aumenta es el tiempo de entrenamiento porque el score del DICE disminuye.
"""
"""
Con resnet18 y pretrained=False:
⏱ Tiempo de entrenamiento: 42.3 s
📊 FCN — Dice en TEST: 0.6246
El DICE score es claramente mucho mas bajo.
"""
"""
¿Qué tipo de errores ves en las máscaras predichas?
Parecier que le cuesta definir correctamente los contornos del polipo, terminan quedando muy "sharp" o captando zonas que no son parte del polipo.
¿En qué imágenes el FCN funciona razonablemente bien? ¿En cuáles falla?
Parece que las imagenes con bordes mas "ondulados" o "sepenteantes" por decir de alguna manera, son las que mas le cuestan
Si tuvieras que llevar este modelo a un endoscopio en producción, ¿qué cambiarías?
Viendo todo lo usado hasta ahora, elegiria el resnet18 con 10-15 epochs ya que es el que menos tiempo tarda sin sacrificar el DICE score que se mantiene igual, pero intentaria mejorar de cierta manera la definicion de los bordes de los polipos, ya que es facil de ver que esto le cuesta.
"""

"""## 5. Modelo 2 — UNET

Ahora pasamos al estándar biomédico. Usamos `segmentation-models-pytorch` que provee UNET con muchos encoders disponibles, todos pre-entrenados en ImageNet.

**Diferencia clave vs. FCN:** UNET tiene **skip connections** que conectan cada nivel del encoder con el nivel correspondiente del decoder. Eso preserva los detalles finos que el encoder pierde durante la compresión — y se va a notar en los bordes de las máscaras predichas.

Mantenemos **mismo encoder (ResNet18), mismo dataset, mismas epochs** — para que la comparación con FCN sea limpia.

"""

import time

unet = smp.Unet(
    encoder_name="resnet18",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
)
print(f"Parámetros entrenables: {sum(p.numel() for p in unet.parameters() if p.requires_grad)/1e6:.2f}M")

t0 = time.time()
unet_history = train_model(unet, train_loader, val_loader, epochs=EPOCHS)
unet_train_time = time.time() - t0

unet_test_dice = evaluate_dice(unet, test_loader)
print(f"\n⏱ Tiempo de entrenamiento: {unet_train_time:.1f} s")
print(f"📊 UNET — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN  — Dice en TEST: {fcn_test_dice:.4f}  (recordatorio)")

"""### Visualizamos las predicciones de UNET

Compará estas máscaras con las del FCN — los bordes deberían ser **mucho más nítidos** y seguir mejor el contorno real del pólipo.

"""

visualize_predictions(unet, test_viz, test_ds, n_samples=4, title="UNET")

"""## 6. 🎯 Tarea 2 — Experimentar con UNET

UNET es flexible. Probá variantes y medí el efecto.

### Mínimo a probar

1. **Otros encoders**: `resnet34`, `resnet50`, `efficientnet-b0`, `mobilenet_v2`. SMP los soporta todos cambiando una sola string. ¿Cuál da mejor Dice? ¿Cuál es más rápido?
2. **Encoder sin pre-entrenar**: `encoder_weights=None`. ¿Cuánto perdés sin ImageNet?
3. **Otra arquitectura "tipo UNET"**: probá `smp.UnetPlusPlus` o `smp.MAnet` con la misma config.

### Reflexión

- ¿En qué tipo de imágenes UNET resuelve cosas que FCN no podía?
- ¿Vale la pena el costo de cómputo extra para ganar X puntos de Dice?
- En un escenario de despliegue real (un colonoscopio inteligente), ¿qué encoder elegirías y por qué?

### Pista de código

```python
unet_v2 = smp.Unet(encoder_name="resnet34", encoder_weights="imagenet",
                   in_channels=3, classes=1)
train_model(unet_v2, train_loader, val_loader, epochs=EPOCHS)
print(f"Test Dice: {evaluate_dice(unet_v2, test_loader):.4f}")
```

"""

# 🎯 TU EXPERIMENTO ACÁ

# Tu código:
import time

unet = smp.MAnet(
    encoder_name="resnet18",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
)
print(f"Parámetros entrenables: {sum(p.numel() for p in unet.parameters() if p.requires_grad)/1e6:.2f}M")

t0 = time.time()
unet_history = train_model(unet, train_loader, val_loader, epochs=EPOCHS)
unet_train_time = time.time() - t0

unet_test_dice = evaluate_dice(unet, test_loader)
print(f"\n⏱ Tiempo de entrenamiento: {unet_train_time:.1f} s")
print(f"📊 UNET — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN  — Dice en TEST: {fcn_test_dice:.4f}  (recordatorio)")

visualize_predictions(unet, test_viz, test_ds, n_samples=4, title="UNET")
"""
Con resnet18:
⏱ Tiempo de entrenamiento: 87.1 s
📊 UNET — Dice en TEST: 0.8183
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Con resnet34:
⏱ Tiempo de entrenamiento: 104.8 s
📊 UNET — Dice en TEST: 0.7996
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Con resnet50:
⏱ Tiempo de entrenamiento: 161.2 s
📊 UNET — Dice en TEST: 0.7489
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Con efficientnet-b0:
⏱ Tiempo de entrenamiento: 105.7 s
📊 UNET — Dice en TEST: 0.8505
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Con mobilenet_v2:
⏱ Tiempo de entrenamiento: 93.0 s
📊 UNET — Dice en TEST: 0.8270
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
El que mejor DICE obtiene es el efficient y el mas rapido es el resnet18 pero mobilenet tambien obtiene una buena relacion DICE/tiempo.
"""
"""
Con resnet18 y sin preentrenar:
⏱ Tiempo de entrenamiento: 87.5 s
📊 UNET — Dice en TEST: 0.5448
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Se puede tanto apreciar en el DICE score como viendo las segmentaciones resultantes que baja considerablemente la calidad.
"""
"""
Con smp.UnetPlusPlus, resnet18 y preentrenado:
⏱ Tiempo de entrenamiento: 190.5 s
📊 UNET — Dice en TEST: 0.8272
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
Con smp.MAnet, resnet18 y preentrenado:
⏱ Tiempo de entrenamiento: 97.8 s
📊 UNET — Dice en TEST: 0.7571
📊 FCN  — Dice en TEST: 0.7854  (recordatorio)
El cambio en los modelos significo un mejor score en el DICE pero considerablemente mas tiempo, llegando a ser mas del doble (son que la difernecia en el DICE se vea tan reflejada como esto)
"""
"""
¿En qué tipo de imágenes UNET resuelve cosas que FCN no podía?
En las que poseen polipos con bordes mas "serpenteantes" como dije en el punto anterior. En este caso sucede tal como dice la consigna, se preservan muchos mas los detalles finos.
¿Vale la pena el costo de cómputo extra para ganar X puntos de Dice?
En un escenario de despliegue real (un colonoscopio inteligente), ¿qué encoder elegirías y por qué?
Viendo los resultados de ambos, elegiria el efficientnet-b0 ya que cuando veo la segmentacion es el que mejor se adecua al polipo, lo que obviamente es mejor ya que significa una menor cantidad de tejido sano siendo definido como parte del polipo.
"""

"""## 7. Modelo 3 — SAM zero-shot

Ahora la prueba más interesante: **SAM no se entrena en Kvasir**. Le pasamos una imagen + un prompt (en este caso, un click en el centro del pólipo) y le pedimos que segmente.

### El protocolo

1. Cargamos los pesos pre-entrenados de SAM ViT-B (~91M parámetros).
2. Para cada imagen del test set, calculamos el **centroide de la máscara ground truth** (simulando un click humano sobre el pólipo).
3. Le pasamos a SAM la imagen + ese único punto como prompt positivo.
4. Comparamos la máscara que devuelve SAM con la ground truth — misma métrica Dice.

> Esto es el protocolo estándar de evaluación zero-shot en la literatura médica de SAM ("1-point evaluation").

"""

from segment_anything import sam_model_registry, SamPredictor
import numpy as np

sam = sam_model_registry["vit_b"](checkpoint=SAM_CKPT).to(device)
sam.eval()
predictor = SamPredictor(sam)
print(f"✅ SAM cargado · {sum(p.numel() for p in sam.parameters())/1e6:.1f}M parámetros")


def mask_centroid(mask_np: np.ndarray):
    """Devuelve (x, y) del centroide de los píxeles foreground, o None si no hay."""
    ys, xs = np.where(mask_np > 0.5)
    if len(xs) == 0:
        return None
    return int(xs.mean()), int(ys.mean())


def sam_predict(img_uint8_hwc: np.ndarray, point_xy: tuple) -> np.ndarray:
    """Predice máscara binaria de SAM con un único point prompt positivo."""
    predictor.set_image(img_uint8_hwc)
    masks, scores, _ = predictor.predict(
        point_coords=np.array([point_xy]),
        point_labels=np.array([1]),
        multimask_output=False,
    )
    return masks[0]  # [H, W] booleano

"""### Evaluamos SAM en el test set

Recorremos todo el test set, ejecutamos SAM con un point prompt por imagen, y calculamos el Dice global.

"""

sam_dices = []
sam_predictions = []  # guardamos algunas para visualizar después

print("Evaluando SAM en test...")
for i in range(len(test_viz)):
    img, mask = test_viz[i]
    img_np  = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    mask_np = mask.squeeze().numpy()

    centroid = mask_centroid(mask_np)
    if centroid is None:
        continue  # caso raro: máscara vacía

    pred_mask = sam_predict(img_np, centroid).astype(np.float32)

    # Dice imagen-a-imagen
    inter = (pred_mask * mask_np).sum()
    union = pred_mask.sum() + mask_np.sum()
    dice = (2 * inter + 1e-6) / (union + 1e-6)
    sam_dices.append(dice)

    # Guardamos las primeras 4 para viz
    if i < 4:
        sam_predictions.append((img_np, mask_np, pred_mask, centroid))

sam_test_dice = float(np.mean(sam_dices))
print(f"\n📊 SAM zero-shot — Dice en TEST: {sam_test_dice:.4f}")
print(f"📊 UNET           — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN            — Dice en TEST: {fcn_test_dice:.4f}")

"""### Visualizamos las predicciones de SAM

El círculo verde marca el **point prompt** (el centroide del ground truth, simulando un click humano). La máscara roja superpuesta es lo que devuelve SAM.

"""

fig, axes = plt.subplots(3, 4, figsize=(14, 10))
for i, (img_np, mask_np, pred_np, centroid) in enumerate(sam_predictions):
    axes[0, i].imshow(img_np)
    axes[0, i].scatter(*centroid, color="lime", s=100, edgecolors="black")
    axes[0, i].set_title(f"#{i} — Imagen + prompt"); axes[0, i].axis("off")

    axes[1, i].imshow(mask_np, cmap="gray"); axes[1, i].set_title("Ground truth"); axes[1, i].axis("off")

    axes[2, i].imshow(img_np)
    axes[2, i].imshow(pred_np, cmap="Reds", alpha=0.5)
    axes[2, i].set_title("SAM (zero-shot)"); axes[2, i].axis("off")
plt.tight_layout(); plt.show()

"""## 8. 🎯 Tarea 3 — Experimentar con SAM

SAM es promptable — el resultado depende mucho del prompt. Probá variantes.

### Mínimo a probar

1. **Bounding box como prompt** (en lugar de un punto). El bbox podés calcularlo desde la máscara ground truth con `np.where`. Esperá un Dice **más alto** que con point.

   ```python
   ys, xs = np.where(mask_np > 0.5)
   bbox = np.array([xs.min(), ys.min(), xs.max(), ys.max()])
   masks, _, _ = predictor.predict(box=bbox, multimask_output=False)
   ```

2. **Prompt con múltiples puntos** (uno positivo en el centro + uno negativo afuera).

3. **`multimask_output=True`**: SAM devuelve 3 máscaras candidatas con distinto score. ¿Te quedarías con la de mejor score? ¿Con la más grande?

### Reflexión

- ¿Cuánto mejora SAM con un bbox vs un point? ¿Qué te dice eso sobre la **información que el prompt aporta**?
- En un workflow clínico real, ¿qué prompt sería más realista que un médico le dé?
- Comparando SAM con UNET fine-tuneada: ¿en qué casos preferirías cada uno?

"""

# 🎯 TU EXPERIMENTO ACÁ

# Tu código:
# 🎯 TAREA 3.1 — SAM con Bounding Box como prompt
"""
sam_bbox_dices = []
sam_bbox_predictions = []

print("Evaluando SAM con bbox en test...")
for i in range(len(test_viz)):
    img, mask = test_viz[i]
    img_np  = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    mask_np = mask.squeeze().numpy()

    # Calcular bbox desde la máscara ground truth
    ys, xs = np.where(mask_np > 0.5)
    if len(xs) == 0:
        continue  # máscara vacía, igual que en el loop de point

    bbox = np.array([xs.min(), ys.min(), xs.max(), ys.max()])

    # Predecir con box prompt
    predictor.set_image(img_np)
    masks, _, _ = predictor.predict(box=bbox, multimask_output=False)
    pred_mask = masks[0].astype(np.float32)

    # Dice imagen-a-imagen
    inter = (pred_mask * mask_np).sum()
    union = pred_mask.sum() + mask_np.sum()
    dice = (2 * inter + 1e-6) / (union + 1e-6)
    sam_bbox_dices.append(dice)

    # Guardamos las primeras 4 para visualizar
    if i < 4:
        sam_bbox_predictions.append((img_np, mask_np, pred_mask, bbox))

sam_bbox_test_dice = float(np.mean(sam_bbox_dices))
print(f"\n📊 SAM bbox  — Dice en TEST: {sam_bbox_test_dice:.4f}")
print(f"📊 SAM point — Dice en TEST: {sam_test_dice:.4f}   ← referencia")
print(f"📊 UNET      — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN       — Dice en TEST: {fcn_test_dice:.4f}")

# ── Visualización ──────────────────────────────────────────────
import matplotlib.patches as patches

fig, axes = plt.subplots(3, 4, figsize=(14, 10))
fig.suptitle("SAM — Bounding Box prompt", fontsize=14, fontweight="bold")

for i, (img_np, mask_np, pred_np, bbox) in enumerate(sam_bbox_predictions):
    # Fila 0: imagen + bbox
    axes[0, i].imshow(img_np)
    x0, y0, x1, y1 = bbox
    rect = patches.Rectangle(
        (x0, y0), x1 - x0, y1 - y0,
        linewidth=2, edgecolor="lime", facecolor="none"
    )
    axes[0, i].add_patch(rect)
    axes[0, i].set_title(f"#{i} — Imagen + bbox")
    axes[0, i].axis("off")

    # Fila 1: ground truth
    axes[1, i].imshow(mask_np, cmap="gray")
    axes[1, i].set_title("Ground truth")
    axes[1, i].axis("off")

    # Fila 2: predicción SAM
    axes[2, i].imshow(img_np)
    axes[2, i].imshow(pred_np, cmap="Reds", alpha=0.5)
    axes[2, i].set_title("SAM (bbox)")
    axes[2, i].axis("off")

plt.tight_layout()
plt.show()
"""
"""
# 🎯 TAREA 3.2 — SAM con múltiples puntos (positivo + negativo)

sam_multi_dices = []
sam_multi_predictions = []

print("Evaluando SAM con multi-point prompt en test...")
for i in range(len(test_viz)):
    img, mask = test_viz[i]
    img_np  = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    mask_np = mask.squeeze().numpy()

    # Punto positivo: centroide del pólipo (igual que antes)
    ys_fg, xs_fg = np.where(mask_np > 0.5)
    if len(xs_fg) == 0:
        continue

    pos_point = (int(xs_fg.mean()), int(ys_fg.mean()))

    # Punto negativo: centroide del FONDO (donde NO hay pólipo)
    ys_bg, xs_bg = np.where(mask_np < 0.5)
    neg_point = (int(xs_bg.mean()), int(ys_bg.mean()))

    # Armar arrays de puntos y labels (1=positivo, 0=negativo)
    point_coords = np.array([pos_point, neg_point])
    point_labels = np.array([1, 0])

    # Predecir
    predictor.set_image(img_np)
    masks, scores, _ = predictor.predict(
        point_coords=point_coords,
        point_labels=point_labels,
        multimask_output=False,
    )
    pred_mask = masks[0].astype(np.float32)

    # Dice imagen-a-imagen
    inter = (pred_mask * mask_np).sum()
    union = pred_mask.sum() + mask_np.sum()
    dice  = (2 * inter + 1e-6) / (union + 1e-6)
    sam_multi_dices.append(dice)

    if i < 4:
        sam_multi_predictions.append((img_np, mask_np, pred_mask, pos_point, neg_point))

sam_multi_test_dice = float(np.mean(sam_multi_dices))
print(f"\n📊 SAM multi-point — Dice en TEST: {sam_multi_test_dice:.4f}")
print(f"📊 SAM bbox        — Dice en TEST: {sam_bbox_test_dice:.4f}")
print(f"📊 SAM point       — Dice en TEST: {sam_test_dice:.4f}")
print(f"📊 UNET            — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN             — Dice en TEST: {fcn_test_dice:.4f}")

# ── Visualización ──────────────────────────────────────────────
fig, axes = plt.subplots(3, 4, figsize=(14, 10))
fig.suptitle("SAM — Multi-point prompt (verde=positivo, rojo=negativo)", fontsize=13, fontweight="bold")

for i, (img_np, mask_np, pred_np, pos, neg) in enumerate(sam_multi_predictions):
    # Fila 0: imagen + ambos puntos
    axes[0, i].imshow(img_np)
    axes[0, i].scatter(*pos, color="lime",  s=120, edgecolors="black", zorder=5, label="positivo")
    axes[0, i].scatter(*neg, color="red",   s=120, edgecolors="black", zorder=5, label="negativo")
    axes[0, i].set_title(f"#{i} — Imagen + prompts")
    axes[0, i].axis("off")

    # Fila 1: ground truth
    axes[1, i].imshow(mask_np, cmap="gray")
    axes[1, i].set_title("Ground truth")
    axes[1, i].axis("off")

    # Fila 2: predicción SAM
    axes[2, i].imshow(img_np)
    axes[2, i].imshow(pred_np, cmap="Reds", alpha=0.5)
    axes[2, i].set_title("SAM (multi-point)")
    axes[2, i].axis("off")

plt.tight_layout()
plt.show()
"""
# 🎯 TAREA 3.3 — SAM con multimask_output=True

sam_best_score_dices  = []
sam_largest_dices     = []
sam_multi_predictions = []

print("Evaluando SAM con multimask_output=True en test...")
for i in range(len(test_viz)):
    img, mask = test_viz[i]
    img_np  = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    mask_np = mask.squeeze().numpy()

    ys, xs = np.where(mask_np > 0.5)
    if len(xs) == 0:
        continue

    centroid = (int(xs.mean()), int(ys.mean()))

    predictor.set_image(img_np)
    masks, scores, _ = predictor.predict(
        point_coords=np.array([centroid]),
        point_labels=np.array([1]),
        multimask_output=True,   # ← devuelve 3 máscaras
    )
    # masks:  (3, H, W) booleano
    # scores: (3,)      confianza de SAM para cada máscara

    # Estrategia A: quedarse con la de mayor score
    best_idx  = int(np.argmax(scores))
    mask_best_score = masks[best_idx].astype(np.float32)

    # Estrategia B: quedarse con la más grande (más píxeles)
    sizes     = masks.sum(axis=(1, 2))
    large_idx = int(np.argmax(sizes))
    mask_largest = masks[large_idx].astype(np.float32)

    def dice(pred, gt):
        inter = (pred * gt).sum()
        return (2 * inter + 1e-6) / (pred.sum() + gt.sum() + 1e-6)

    sam_best_score_dices.append(dice(mask_best_score, mask_np))
    sam_largest_dices.append(dice(mask_largest,       mask_np))

    if i < 4:
        sam_multi_predictions.append((
            img_np, mask_np, masks, scores, centroid
        ))

print(f"\n📊 SAM mejor score  — Dice en TEST: {np.mean(sam_best_score_dices):.4f}")
print(f"📊 SAM más grande   — Dice en TEST: {np.mean(sam_largest_dices):.4f}")
print(f"📊 SAM multi-point  — Dice en TEST: {sam_multi_test_dice:.4f}")
print(f"📊 SAM bbox         — Dice en TEST: {sam_bbox_test_dice:.4f}")
print(f"📊 SAM point        — Dice en TEST: {sam_test_dice:.4f}")
print(f"📊 UNET             — Dice en TEST: {unet_test_dice:.4f}")
print(f"📊 FCN              — Dice en TEST: {fcn_test_dice:.4f}")

# ── Visualización ──────────────────────────────────────────────
fig, axes = plt.subplots(5, 4, figsize=(14, 16))
fig.suptitle("SAM — multimask_output=True (3 candidatas por imagen)", fontsize=13, fontweight="bold")

row_titles = ["Imagen + prompt", "Máscara 0", "Máscara 1", "Máscara 2", "Ground truth"]
for ax, title in zip(axes[:, 0], row_titles):
    ax.set_ylabel(title, fontsize=10, fontweight="bold")

for i, (img_np, mask_np, masks, scores, centroid) in enumerate(sam_multi_predictions):
    sizes = masks.sum(axis=(1, 2))
    best  = int(np.argmax(scores))
    large = int(np.argmax(sizes))

    # Fila 0: imagen con prompt
    axes[0, i].imshow(img_np)
    axes[0, i].scatter(*centroid, color="lime", s=120, edgecolors="black", zorder=5)
    axes[0, i].set_title(f"#{i}")
    axes[0, i].axis("off")

    # Filas 1-3: las 3 máscaras candidatas
    for m_idx in range(3):
        ax = axes[m_idx + 1, i]
        ax.imshow(img_np)
        ax.imshow(masks[m_idx].astype(float), cmap="Reds", alpha=0.5)
        label = f"score={scores[m_idx]:.2f} | px={int(sizes[m_idx])}"
        markers = []
        if m_idx == best:  markers.append("★score")
        if m_idx == large: markers.append("★grande")
        title_str = label + (f"\n{' '.join(markers)}" if markers else "")
        ax.set_title(title_str, fontsize=8)
        ax.axis("off")

    # Fila 4: ground truth
    axes[4, i].imshow(mask_np, cmap="gray")
    axes[4, i].set_title("Ground truth")
    axes[4, i].axis("off")

plt.tight_layout()
plt.show()
"""
Con bbox:
📊 SAM bbox  — Dice en TEST: 0.9013
📊 SAM point — Dice en TEST: 0.7193   ← referencia
📊 UNET      — Dice en TEST: 0.7571
📊 FCN       — Dice en TEST: 0.7854
Con multiples puntos:
📊 SAM multi-point — Dice en TEST: 0.7045
📊 SAM bbox        — Dice en TEST: 0.9013
📊 SAM point       — Dice en TEST: 0.7193
📊 UNET            — Dice en TEST: 0.7571
📊 FCN             — Dice en TEST: 0.7854
Con multimask:
📊 SAM mejor score  — Dice en TEST: 0.5908
📊 SAM más grande   — Dice en TEST: 0.3637
📊 SAM multi-point  — Dice en TEST: 0.7045
📊 SAM bbox         — Dice en TEST: 0.9013
📊 SAM point        — Dice en TEST: 0.7193
📊 UNET             — Dice en TEST: 0.7571
📊 FCN              — Dice en TEST: 0.7854
"""
"""
¿Cuánto mejora SAM con un bbox vs un point? ¿Qué te dice eso sobre la información que el prompt aporta?
Se puede ver que con bbox el DICE mejora ampliamente, lo que me dice que cuanto mejor sea el prompt definiendo la zona de interes, mejor sera el resultado en la segmentacion.
En un workflow clínico real, ¿qué prompt sería más realista que un médico le dé?
Mas alla de que obviamente la mas "simple" seria la de un solo punto, considero que la del bbox sigue teniendo cierta simplicidad para que el profesional la utilice y esta es claramente muy superior a la de un solo punto, por lo que en mi opinion seria la mas realista a implementar.
Comparando SAM con UNET fine-tuneada: ¿en qué casos preferirías cada uno?
En un caso donde el medico este hands-on durante la deteccion, preferiria el SAM debido a el alto puntaje que obtuvo el bbox pero en uno donde esto no suceda, elegiria la UNET fine-tuneada
"""

"""## 9. Comparativa final

Juntamos todo en una tabla. Cada modelo gana en una dimensión distinta.

"""

import pandas as pd

n_params_fcn  = sum(p.numel() for p in fcn.parameters())  / 1e6
n_params_unet = sum(p.numel() for p in unet.parameters()) / 1e6
n_params_sam  = sum(p.numel() for p in sam.parameters())  / 1e6

results = pd.DataFrame({
    "Modelo":             ["FCN (ResNet18)",       "UNET (ResNet18)",      "SAM ViT-B (zero-shot)"],
    "Dice (test)":        [f"{fcn_test_dice:.4f}", f"{unet_test_dice:.4f}", f"{sam_test_dice:.4f}"],
    "Parámetros (M)":     [f"{n_params_fcn:.1f}",  f"{n_params_unet:.1f}",  f"{n_params_sam:.1f}"],
    "Tiempo entrenamiento (s)": [f"{fcn_train_time:.1f}", f"{unet_train_time:.1f}", "0 (zero-shot)"],
    "Necesita prompt": ["No", "No", "Sí (point/box/text)"],
})
results

"""### Lectura de la tabla

- **UNET** suele dar el **mejor Dice** — está hecha para esto, fue fine-tuneada con tus datos, los bordes salen nítidos.
- **FCN** queda atrás — los bordes borrosos cuestan unos puntos de Dice. Fue lo esperado de la teoría.
- **SAM** es competitivo **sin haber visto Kvasir** — esa es la magia del foundation model. La contraparte: necesita un humano que le diga dónde mirar.

**Cuándo preferir cada uno (regla práctica):**
- **UNET** → producción clínica, métrica medible, contornos críticos.
- **SAM** → anotación asistida, exploración rápida de un dataset nuevo, prototipos.
- **FCN** → casi nunca en producción real; útil como baseline didáctico para entender por qué UNET fue tan importante.

## 10. 🎯 Tarea opcional 1 — SAM 2 sobre el dataset de pólipos

> 📝 **Aunque esta tarea sea opcional, suma puntos a la nota final.** Hacerla muestra interés y compromiso, y queda registrada en la entrega.

SAM 2 (Meta, julio 2024) extiende SAM 1 con:
- Un **encoder Hiera** (jerárquico) más eficiente que el ViT-H original.
- Soporte nativo para **video** vía un módulo de memoria.
- Mejor rendimiento en imagen estática **incluso sin tocar el módulo de video**.

### Tu tarea

Replicá la evaluación zero-shot de SAM 1 que ya hiciste, **pero usando SAM 2**, y compará los Dice scores.

### Pista de instalación

```bash
!pip install -q sam2
```

### Pista de API

```python
from sam2.sam2_image_predictor import SAM2ImagePredictor
from sam2.build_sam import build_sam2_hf

# Carga el modelo desde Hugging Face — sin bajar checkpoints a mano
predictor_v2 = SAM2ImagePredictor.from_pretrained("facebook/sam2.1-hiera-base-plus")

# La API de inferencia es muy parecida a SAM 1
predictor_v2.set_image(img_uint8_hwc)
masks, scores, _ = predictor_v2.predict(
    point_coords=np.array([centroid]),
    point_labels=np.array([1]),
    multimask_output=False,
)
```

> Las variantes son `sam2.1-hiera-tiny`, `sam2.1-hiera-small`, `sam2.1-hiera-base-plus`, `sam2.1-hiera-large`. Empezá con `base-plus` — buena calidad y razonable en T4.

### Reflexión

- ¿Cuánto mejora el Dice respecto a SAM 1?
- ¿La mejora viene del encoder Hiera, del decoder, o de ambos?
- En aplicaciones biomédicas estáticas (no video), ¿vale la pena el cambio?

### Recursos

- Repo: <https://github.com/facebookresearch/sam2>
- Tutorial: <https://www.labellerr.com/blog/learn-sam-2-in-minutes/>
"""

# 🎯 TAREA OPCIONAL 1 — SAM 2 sobre Kvasir
# Objetivo: replicar la evaluación zero-shot que hiciste con SAM 1, pero usando SAM 2,
#           y comparar los Dice scores.

# !pip install -q sam2
# from sam2.sam2_image_predictor import SAM2ImagePredictor
# predictor_v2 = SAM2ImagePredictor.from_pretrained("facebook/sam2.1-hiera-tiny")

# Tu código:
# 🎯 TAREA OPCIONAL 1 — SAM 2 sobre Kvasir

!pip install -q sam2

from sam2.sam2_image_predictor import SAM2ImagePredictor
import numpy as np

# Carga desde HuggingFace, sin bajar checkpoints a mano
predictor_v2 = SAM2ImagePredictor.from_pretrained("facebook/sam2.1-hiera-large")
print("✅ SAM 2 cargado")

# ── Evaluación zero-shot con point prompt ──────────────────────
sam2_dices       = []
sam2_predictions = []

print("Evaluando SAM 2 en test...")
for i in range(len(test_viz)):
    img, mask = test_viz[i]
    img_np  = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    mask_np = mask.squeeze().numpy()

    ys, xs = np.where(mask_np > 0.5)
    if len(xs) == 0:
        continue

    centroid = (int(xs.mean()), int(ys.mean()))

    # SAM 2 usa context manager para inferencia
    with torch.inference_mode():
        predictor_v2.set_image(img_np)
        masks, scores, _ = predictor_v2.predict(
            point_coords=np.array([centroid]),
            point_labels=np.array([1]),
            multimask_output=False,
        )

    pred_mask = masks[0].astype(np.float32)

    inter = (pred_mask * mask_np).sum()
    union = pred_mask.sum() + mask_np.sum()
    dice  = (2 * inter + 1e-6) / (union + 1e-6)
    sam2_dices.append(dice)

    if i < 4:
        sam2_predictions.append((img_np, mask_np, pred_mask, centroid))

sam2_test_dice = float(np.mean(sam2_dices))

# ── Resultados ─────────────────────────────────────────────────
print(f"\n📊 SAM 2 (point) — Dice en TEST: {sam2_test_dice:.4f}  ← nuevo")
print(f"📊 SAM 1 (point) — Dice en TEST: {sam_test_dice:.4f}")
print(f"📊 SAM 1 (bbox)  — Dice en TEST: {sam_bbox_test_dice:.4f}")
print(f"\n🔺 Mejora SAM 2 vs SAM 1: {(sam2_test_dice - sam_test_dice)*100:+.2f} pp")

# ── Visualización comparativa SAM 1 vs SAM 2 ──────────────────
fig, axes = plt.subplots(4, 4, figsize=(14, 13))
fig.suptitle("SAM 1 vs SAM 2 — mismo point prompt, mismo test set", fontsize=13, fontweight="bold")

for i, ((img_np, mask_np, pred_sam1, centroid), (_, _, pred_sam2, _)) in enumerate(
    zip(sam_predictions, sam2_predictions)
):
    dice1 = (2*(pred_sam1*mask_np).sum() + 1e-6) / (pred_sam1.sum() + mask_np.sum() + 1e-6)
    dice2 = (2*(pred_sam2*mask_np).sum() + 1e-6) / (pred_sam2.sum() + mask_np.sum() + 1e-6)

    # Fila 0: imagen + prompt
    axes[0, i].imshow(img_np)
    axes[0, i].scatter(*centroid, color="lime", s=120, edgecolors="black", zorder=5)
    axes[0, i].set_title(f"#{i} — prompt"); axes[0, i].axis("off")

    # Fila 1: ground truth
    axes[1, i].imshow(mask_np, cmap="gray")
    axes[1, i].set_title("Ground truth"); axes[1, i].axis("off")

    # Fila 2: SAM 1
    axes[2, i].imshow(img_np)
    axes[2, i].imshow(pred_sam1, cmap="Reds", alpha=0.5)
    axes[2, i].set_title(f"SAM 1 · Dice={dice1:.3f}"); axes[2, i].axis("off")

    # Fila 3: SAM 2
    axes[3, i].imshow(img_np)
    axes[3, i].imshow(pred_sam2, cmap="Blues", alpha=0.5)
    axes[3, i].set_title(f"SAM 2 · Dice={dice2:.3f}"); axes[3, i].axis("off")

plt.tight_layout()
plt.show()

"""
Con sam2.1-hiera-base-plus:
📊 SAM 2 (point) — Dice en TEST: 0.7512  ← nuevo
📊 SAM 1 (point) — Dice en TEST: 0.7193
📊 SAM 1 (bbox)  — Dice en TEST: 0.9013
📊 UNET          — Dice en TEST: 0.7571
📊 FCN           — Dice en TEST: 0.7854

🔺 Mejora SAM 2 vs SAM 1: +3.19 pp
Con sam2.1-hiera-tiny:
📊 SAM 2 (point) — Dice en TEST: 0.7327  ← nuevo
📊 SAM 1 (point) — Dice en TEST: 0.7193
📊 SAM 1 (bbox)  — Dice en TEST: 0.9013

🔺 Mejora SAM 2 vs SAM 1: +1.34 pp
Con sam2.1-hiera-small:
📊 SAM 2 (point) — Dice en TEST: 0.7640  ← nuevo
📊 SAM 1 (point) — Dice en TEST: 0.7193
📊 SAM 1 (bbox)  — Dice en TEST: 0.9013

🔺 Mejora SAM 2 vs SAM 1: +4.47 pp
Con sam2.1-hiera-base-plus:
📊 SAM 2 (point) — Dice en TEST: 0.7512  ← nuevo
📊 SAM 1 (point) — Dice en TEST: 0.7193
📊 SAM 1 (bbox)  — Dice en TEST: 0.9013

🔺 Mejora SAM 2 vs SAM 1: +3.19 pp
Con sam2.1-hiera-large:
📊 SAM 2 (point) — Dice en TEST: 0.7624  ← nuevo
📊 SAM 1 (point) — Dice en TEST: 0.7193
📊 SAM 1 (bbox)  — Dice en TEST: 0.9013

🔺 Mejora SAM 2 vs SAM 1: +4.31 pp

Las que parecen haber dado un mejor DICE score fueron la small y la large, aunque todas dieron un puntaje bastante parecido.
"""

"""## 11. 🎯 Tarea opcional 2 — SAM 3 sobre el dataset de pólipos

> 📝 **Aunque esta tarea sea opcional, suma puntos a la nota final.** Hacerla muestra interés y compromiso, y queda registrada en la entrega.

SAM 3 (Meta, noviembre 2025) introduce capacidades nuevas:
- **Prompts de texto** (vocabulario abierto): podés segmentar pidiendo *"polyp"* en lenguaje natural — sin clicks.
- **Concept prompts** combinados con prompts geométricos.
- 848M de parámetros, mejoras significativas sobre SAM 2 en open-vocabulary.

### Tu tarea

Probá SAM 3 sobre Kvasir de **dos formas**:

**A. Con prompt de texto (la novedad)** — `text_prompt = "polyp"`. Comparalo con SAM 1 y SAM 2.

**B. Con prompt geométrico** (el centroide, igual que antes). Comparalo también — ¿la calidad geométrica de SAM 3 es mejor que la de SAM 2 en este dominio?

### Pista de instalación

```bash
!git clone https://github.com/facebookresearch/sam3.git
!cd sam3 && pip install -e .
```

### Pista de API

```python
from sam3 import build_sam3_image_model, Sam3Processor

model = build_sam3_image_model(checkpoint="sam3_image.pt")
processor = Sam3Processor(model)

state = processor.set_image(img_uint8_hwc)

# A) Prompt de texto:
processor.set_text_prompt(state=state, prompt="polyp")
results = processor.get_results(state=state)
# results contiene: masks, boxes, scores

# B) Prompt geométrico (similar a SAM 1/2):
processor.add_geometric_prompt(state=state,
                                point_coords=[centroid],
                                point_labels=[1])
```

### Reflexión

- ¿Qué tan bien funciona "polyp" como prompt de texto sobre imágenes endoscópicas? ¿Detecta múltiples pólipos sin que se le digan dónde están?
- Si SAM 3 con texto funciona razonablemente bien zero-shot, ¿qué implicancia clínica tiene? (Pista: ya no hace falta ni que el médico clickee.)
- ¿Cuál es el orden esperado de calidad: SAM 1 < SAM 2 < SAM 3? ¿Lo confirmaste empíricamente?

### Recursos

- Repo: <https://github.com/facebookresearch/sam3>
- Getting Started: <https://deepwiki.com/facebookresearch/sam3/2-getting-started>
- Tutorial: <https://stable-learn.com/en/sam3-segment-anything-model-tutorial/>

"""

# 🎯 TAREA OPCIONAL 2 — SAM 3 sobre Kvasir
# Objetivo: probar SAM 3 con prompt de texto ("polyp") y con prompt geométrico,
#           comparando ambos contra SAM 1 y SAM 2.

# !git clone https://github.com/facebookresearch/sam3.git
# !cd sam3 && pip install -e .

# from sam3 import build_sam3_image_model, Sam3Processor
# model = build_sam3_image_model(checkpoint=...)
# processor = Sam3Processor(model)

# Tu código:

"""## 12. 🎯 Tarea opcional 3 — Multi-clase con BUSI

> 📝 **Aunque esta tarea sea opcional, suma puntos a la nota final.** Hacerla muestra interés y compromiso, y queda registrada en la entrega.

Hasta acá todo fue **binario** (pólipo vs. fondo). Probemos un caso más realista: **BUSI (Breast Ultrasound)**, que tiene **3 clases** — lesión benigna, lesión maligna y fondo.

### Tu tarea

1. Cargar `BusiMSBench` con la misma API.
2. Entrenar una UNET con `classes=3` (en lugar de 1).
3. Reemplazar la `DiceLoss` por `MULTICLASS_MODE`.
4. Calcular Dice por clase y reportar.

### Pistas

```python
from medsegbench import BusiMSBench
busi_train = BusiMSBench(split="train", size=256, download=True,
                          transform=img_train_tf, target_transform=mask_tf)

unet_busi = smp.Unet(encoder_name="resnet18", encoder_weights="imagenet",
                      in_channels=3, classes=3)

loss_fn = smp.losses.DiceLoss(smp.losses.MULTICLASS_MODE, from_logits=True)
```

> En multi-clase, las máscaras vienen con valores `{0, 1, 2}` en lugar de `{0, 1}`. Vas a tener que adaptar el `dice_score` para que calcule un Dice por clase y promedie.

### Reflexión

- ¿UNET separa bien benigno de maligno o tiende a confundirlos?
- ¿Cuál clase es más difícil? ¿Por qué (visualmente)?
- En medicina, **distinguir benigno de maligno tiene consecuencias clínicas**. Si tu UNET confunde estas dos clases, ¿qué impacto tendría en producción?

"""

# 🎯 TAREA BONUS — TU CÓDIGO ACÁ

"""## 13. Cierre

En esta notebook recorriste los **tres paradigmas de segmentación** que vimos en la clase teórica:

1. **FCN** → la idea base ("clasificar cada píxel"). Funciona, pero los bordes salen borrosos. Histórico.
2. **UNET** → el estándar biomédico. Skip connections + arquitectura simétrica → bordes nítidos. Casi siempre la mejor opción cuando tenés datos etiquetados.
3. **SAM** → foundation model promptable. **Cero entrenamiento** sobre tu dominio, resultados sorprendentemente buenos con un click.

### Lo que conviene llevarse

- En medicina, **el borde es el dato**. UNET sigue ganando cuando la métrica clínica importa.
- SAM no compite con UNET — la **complementa**. Sirve para anotar más rápido, explorar datasets nuevos, o construir herramientas interactivas para clínicos.
- La elección depende del problema, no de "cuál es mejor en abstracto".

### Para seguir explorando

- **MedSAM** — fine-tuning de SAM sobre datasets médicos masivos (mejora mucho el zero-shot en imagen médica).
- **nnU-Net** — el framework que automatiza el entrenamiento de UNET y gana competencias médicas año tras año.
- **Otros datasets de MedSegBench** — `Isic2018MSBench` (dermatología), `DriveMSBench` (vasos retinianos), `Promise12MSBench` (próstata MRI). Cambiás una línea y reusás todo el código de esta notebook.
- **TransUNet, SwinUNet** — variantes de UNET con backbones Transformer.

---

**Profesores:** Paulo Veiga · Marco Sanchez Sorondo
**Materia: IA para Ingeniería Biomédica**

"""